Creating Minion for Boss Mode
Frotty/EBR pull request #2
Opened 2016-07-29 00:43 UTC by kari0003

Created basic skeleton for minion
There is no way (ability or function) to create a minion yet.
Feel free to leave this PR open, so i can continue later on ( i will only be back on sunday :S)

2016-07-31 22:38 UTC, Frotty commented on wurst/boss/Minion.wurst
> +            IssuePointOrder(actor, "move", target.pos.x, target.pos.y)
use extension functions

2016-08-04 00:05 UTC, Frotty commented on wurst/boss/Boss.wurst
> +				// TODO play sound effect
do todos :P

2016-08-04 00:06 UTC, Frotty commented on wurst/boss/Minion.wurst
> +    construct(unit existing)
this is only used for startmazes, but i guess this could be a general enemy also?

2016-08-04 00:07 UTC, Frotty commented on wurst/boss/Boss.wurst
>  public class Boss extends SetupObject
add ability to boss in code so it's independent from map

2016-08-04 00:09 UTC, Frotty commented on wurst/boss/Minion.wurst
> +    override function update()
I'm not sure if ordering each tick is best performance wise. Maybe just order an attack?

2016-08-04 00:10 UTC, Frotty commented on wurst/boss/Minion.wurst
> +    function selectTarget()
add secret zombie cheese item that throws bait to lure them away :3

2016-08-04 17:34 UTC, kari0003 commented on wurst/boss/Minion.wurst
> +    construct(unit existing)
yes indeed it could be, however in any case; we dont need this constructor.

2016-08-04 17:42 UTC, kari0003 commented on wurst/boss/Boss.wurst
>  public class Boss extends SetupObject
Where should i add it? .j file?

2016-08-04 17:55 UTC, Frotty commented on wurst/boss/Boss.wurst
>  public class Boss extends SetupObject
in the Boss constructor

2017-02-11 02:08 UTC, Frotty requested changes

2017-02-11 02:08 UTC, Frotty commented on wurst/boss/Minion.wurst
> +class MinionData
Class not necessary if it only has one member

2017-02-11 02:08 UTC, Frotty commented on wurst/boss/Minion.wurst
> +            getTimer()..start(3, function Minion.removeAfterDeath)..setData(new MinionData(this) castTo int)
Use doAfter() for the timed stuff

2017-02-11 02:08 UTC, Frotty commented on wurst/boss/Minion.wurst
> +        if target == null or target.alive != true or target.getCurrentRegion() != this.getCurrentRegion()
target.alive != true -> not target.alive

2017-02-11 02:08 UTC, Frotty commented on wurst/boss/Minion.wurst
> +        hpBar.setPosXY(pos.x - 50, pos.y + 50)
use casecade operator (..)

2017-02-11 02:08 UTC, Frotty commented on wurst/boss/Minion.wurst
> +            selectTarget()
I think it is not a good idea to check for targets every tick. 
You could instead increase collisionsize and wake the minion up using onSensor (from the class Minion extends)
Or you add a buff to the minion that checks for targets - buffs are only updated 4 times per second.

2017-02-11 02:08 UTC, Frotty commented on wurst/boss/Minion.wurst
> +    function selectTarget()
It would be nice to have a maximum distance to search for targets

2017-02-11 02:08 UTC, Frotty commented on wurst/boss/Minion.wurst
> +                actor.setFacing(pos.angleTo2d(target.pos))
Please add a maximum guard distance or some other way to stop the minion chasing the escapers. Maybe there should be the posibilitiy of a safe zone somehow

2017-02-11 02:08 UTC, Frotty commented on wurst/boss/Minion.wurst
> +                let entity = u.getEntity()
plz add kewl spec1al effx and texttags and shit 👍 👍

2017-02-11 02:08 UTC, Frotty commented on wurst/boss/WeaponTypes.wurst
> +function damageTarget(Entity entity, Escaper escaper, real damage)
not good if we have to extend this one function for everything that should be procced by damage.
We should do this in another way, maybe via buffs or listeners

2017-02-19 19:50 UTC, Frotty approved these changes
Thanks krarolinorio

2017-02-19 19:50 UTC, merged